### ISSUE TITLE
Wrong ClickState Constants

### ISSUE THREAD

**Issue by wasupandceacar** [Mempler/rplpa#2]
It seems that the ClickState constants written in [consts.go](https://github.com/Mempler/rplpa/blob/master/consts.go) is not right.
I modified the constant to:

	const (
		LEFTCLICK  = 1 << 0
		RIGHTCLICK = 1 << 1
		KEY1       = 1 << 2
		KEY2       = 1 << 3
		SMOKE      = 1 << 4
	)
And it works well.

**Comment by Mempler** [comment]
Oh, would be great if you make a PR then!

**Comment by wasupandceacar** [comment]
NP (｀・ω・´)
